name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: Set up eksctl
      uses: moia-oss/setup-eksctl@v1
      with:
        version: 'latest' # You can specify a version like '0.57.0'

    - name: Verify eksctl installation
      run: eksctl version    

    - name: Create EKS cluster
      run: |
        eksctl create cluster \
          --name my-cluster \
          --region ap-south-1 \
          --nodegroup-name linux-nodes \
          --node-type t2.micro\
          --nodes 3 \
          --nodes-min 1 \
          --nodes-max 4 \
          --managed

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name my-cluster --region ap-south-1

    - name: Deploy application
      run: |
        kubectl apply -f k8s/deployment.yaml
