name: Deployment On K8s Cluster
 
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
 
permissions:
  id-token: write
  contents: read
 
jobs:
  Deploy_On_Cluster:
    name: Deploy Application On Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
 
      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.1'
        id: install
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
 
      - name: Create EKS Cluster
        run: |
          eksctl create cluster --name mycluster --region ap-south-1 --node-type t2.micro
          aws eks update-kubeconfig --region ap-south-1 --name mycluster
 
      - name: Update KubeConfig
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
 
      - name: Deploy to EKS
        run: kubectl run nginx --image=nginx
 
      
